services:
  postgres:
    image: postgres:16
    container_name: gratitude-coo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gratitude_coo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/monolithic:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data: 